### PR TITLE
Fixed autoloading

### PR DESCRIPTION
**Pull request by brabijan**

### CODE REVIEW

**Comment by fprochazka** [comment]
FYI this is not really meant to be used as a dependency, but more like examples.

**Comment by brabijan** [comment]
i was confused, because there is composer package and it's not mentioned anywhere. sorry for that

**Comment by fprochazka** [comment]
I didn't mean for you to close the PR, I just wanned to make you aware. This is not a stable library.

**Comment by brabijan** [comment]
Is there anything i can help with? This could be good tester extension

**Comment by fprochazka** [comment]
I'm not sure I want this to be used as a dependency...

**Pull request merged**
